name: null
channels:
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - cudnn=7.6.5_10.2
  - astropy
  - pegasus-wms.api
  - GitPython
  - alembic
  - attrs
  - backcall
  - cliff
  - cmaes
  - cmd2
  - colorama
  - colorlog
  - cycler
  - decorator
  - greenlet
  - imageio
  - ipython
  - ipython_genutils
  - jedi
  - joblib
  - kiwisolver
  - Mako
  - MarkupSafe
  - matplotlib
  - networkx
  - numpy
  - optuna
  - packaging
  - pandas
  - parso
  - pbr
  - pexpect
  - pickleshare
  - Pillow
  - prettytable
  - prompt-toolkit
  - ptyprocess
  - Pygments
  - pyparsing
  - pyperclip
  - python-dateutil
  - python-editor
  - pytz
  - PyWavelets
  - PyYAML
  - scikit-image
  - scikit-learn
  - scikit-plot
  - scipy
  - seaborn
  - six
  - SQLAlchemy
  - stevedore
  - threadpoolctl
  - tifffile
  - tqdm
  - traitlets
  - typing-extensions
  - wcwidth
  - python=3.7
  - pytorch=1.5
  - torchvision  
