name: cosmoflow 

channels:
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
  - conda-forge
  - defaults

dependencies:
  #- horovod==0.19.0
  - tensorflow-gpu==1.13.1
  - pandas==1.0.5
  - pip
  - pip:
    - scikit-learn
