name: ewa 

channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - theano
  - scikit-learn
  - h5py
  - matplotlib==3.4.2
  - netCDF4
  - pandas
  - cudnn=8.0
  - pip
  - pip:
    - https://github.com/Lasagne/Lasagne/archive/master.zip
