name: cosmoflow 

channels:
  - https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/
  - conda-forge
  - defaults

dependencies:
  - horovod==0.19.0
  - tensorflow-gpu==2.1.3
  - numpy
  - pandas
  - pip
  - pip:
    - scikit-learn
